# Generated by Django 5.0.6 on 2024-08-08 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='header_image',
            field=models.URLField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_image',
            field=models.URLField(blank=True, default='', null=True),
        ),
    ]
